--liquibase formatted sql
--changeset tianjl:tianjingle-20191122-1
-- INSERT INTO `resource` (`id`, `resource_name`, `resource_url`, `content`, `flag`) VALUES ('1', '菜单管理', '/menuManager', 'menuManager', 'Y');
-- INSERT INTO `resource` (`id`, `resource_name`, `resource_url`, `content`, `flag`) VALUES ('2', '资源管理', '/resourceManager', 'ResourceManager', 'Y');
-- INSERT INTO `resource` (`id`, `resource_name`, `resource_url`, `content`, `flag`) VALUES ('3', '角色管理', '/roleManager', 'roleManager', 'Y');
-- INSERT INTO `resource` (`id`, `resource_name`, `resource_url`, `content`, `flag`) VALUES ('4', '用户管理', '/userManager', 'UserManager', 'Y');
-- INSERT INTO `resource` (`id`, `resource_name`, `resource_url`, `content`, `flag`) VALUES ('5', '机构管理', '/organization', 'Organization', 'Y');
-- INSERT INTO `resource` (`id`, `resource_name`, `resource_url`, `content`, `flag`) VALUES ('6', '我的项目', '/myProjectManager', 'MyProjectManager', 'Y');
